### ISSUE TITLE
Stop Original page from scrolling when modal is up

### ISSUE THREAD

**Issue by davchana** [madprops/Msg#1]
When modal pop is displayed, is it possible to stop the original underlying page from getting any scroll touch, thus freezing it in its place, until the modal is closed by clicking on grey overlay.?

**Comment by madprops** [comment]
Fixed in [v2.6.0](https://github.com/madprops/Msg/releases/tag/v2.6.0) -- Tested in Chrome, Firefox, Edge and Vivaldi. Thanks!

**Comment by madprops** [comment]
Making a fix to allow normal scrolling on inner scrollable elements.

**Comment by madprops** [comment]
[v2.6.2](https://github.com/madprops/Msg/releases/tag/v2.6.2)

**Comment by madprops** [comment]
It properly works here [v2.6.6](https://github.com/madprops/Msg/releases/tag/v2.6.6)

**Comment by madprops** [comment]
I decided to remove this feature. I got it to work in most cases, but certain cases, and in certain browsers, some things didn't work as expected. It's just too messy, I decided to leave it to the browsers to handle this, hopefully in a better way in the future. Last version with this feature was v3.0.0

**Comment by badggit** [comment]
Hi
Unfortunately it's still actual and make this great lib useless.
How to fix it? This not helping:
```
      this.msg = Msg({
        enable_titlebar: true,
        scroll_on_show: false,
        lock: true,
      });
```

Upd: it was because of popular scrollbar hack```

html {
  overflow-x: hidden;
  margin-right: calc(-1 * (100vw - 100%));
}
```
Please keep in mind, that some people use overflow in <html>, not only in <body>.
Thanks for library, it's really useful.

**Comment by madprops** [comment]
Hi

Hmm .. would an option to specify which element to lock help you?

Thinking of something like: 

`locked_element: document.documentElement`
`locked_element: document.body`

etc

**Comment by madprops** [comment]
New version released: https://github.com/madprops/Msg/releases/tag/v7.9.0

`locked_element (Default: "body"): String argument for document.querySelector() to find the element to be locked.`
