### ISSUE TITLE
How was the Msg github page generated?

### ISSUE THREAD

**Issue by davchana** [madprops/Msg#2]
https://madprops.github.io/Msg/

Was this coded by hand? Or what plugin/framework/software you used? Thanks.

**Comment by davchana** [comment]
Not Msg script, but the html code for github page.

**Comment by madprops** [comment]
Hi, I made it by hand.

**Comment by madprops** [comment]
@davchana your issue inspired me to create a node tool to create documentations similar to this, but with much more features: https://madprops.github.io/Doctor/
