### ISSUE TITLE
Script won't work in Chrome 41

### ISSUE THREAD

**Issue by badggit** [madprops/Msg#5]
Hi
msg.js and msg.min.js won't work in Chrome 41 (and some other versions) because of things like this:
var factory = function(options={})

So, it's better to avoid of using default values in the function header. Some companies still using old Chrome versions because of plugins.
It's up to you fix that or not of course,

Also, can you please add "export default Msg" or something from the moders web, because now it's very hard to use your library with webpack.

Thanks for the library!

**Comment by madprops** [comment]
Hi. Sorry to hear you're having problems using this library. Unfortunately I decided I'm not going to drop support for modern features like default parameters. The module pattern used should be updated to conform to more modern standards, but I'm not sure which one to use yet. If anything, feel free to fork it and make your own changes. Thanks.

**Comment by badggit** [comment]
Thanks for your answer and support.
I use webpack + babel + react.
 
The situation is very strange because, on the one hand, you support only modern browsers (and this is right decision!), but on the other hand, you don't support modern web structure (what is bad) like imports ("export default") or at least UMD/CommonJS ("module.exports"). You use global object what is really legacy way.
   
By the way, if you still want to support that legacy global objects method, you can use UMD pattern. It will add support for current method + CommonJS + AMD.
https://github.com/umdjs/umd/blob/master/templates/returnExports.js

**Comment by madprops** [comment]
Hey, 

Just made a big re-write and now using this module pattern:

```
try 
{
	module.exports = Msg
}

catch(e){}
```

Which allows the library to work with webpack (just tested it), as well as be imported as a <script> in html. Please give it a try and tell me if it's working

https://github.com/madprops/Msg/releases/tag/v9.0.1

**Comment by badggit** [comment]
Now it works perfect. Thank you!
